### ISSUE TITLE
Load From Checkpoint

### ISSUE THREAD

**Issue by adamhrv** [hangzhaomit/semantic-segmentation-pytorch#1]
Is it not possible to load from a checkpoint? 

When using the same `--id` parameter the `train.py` script will restart at Epoch 0, but it would be very helpful if the training could restart where it left off.

Alternatively, is there a PyTorch pretrained model for the ADE20K dataset to get started with?

**Comment by hangzhaomit** [comment]
@adamhrv This is in my plan. I will release the model weights soon.

**Comment by danzschulman** [comment]
I would also appreciate a pretrained model :)
