### ISSUE TITLE
It seems that the link to resnet50 is broke and when will you provide the model for resnet 100 and resnet 150

### ISSUE THREAD

**Issue by gaopeng-eugene** [hangzhaomit/semantic-segmentation-pytorch#11]

**Comment by gaopeng-eugene** [comment]
wget resnet50 will return ERROR404: Not Found

**Comment by hangzhaomit** [comment]
Sorry that it was deleted by accident, re-training now.
I probably do not have enough computing resources for training larger models, which usually takes a week to pretrain.

**Comment by gaopeng-eugene** [comment]
Is it possible to pretrain the model with small input size?

**Comment by hangzhaomit** [comment]
@gaopeng-eugene 
It is recommended to pretrain with small segSize, which takes much less memory. It improves ResNet50 model by around 2%.

**Comment by hangzhaomit** [comment]
Broken resnet50 model is now fixed. Resnet100 will come after 3-4 days.
