### ISSUE TITLE
GPU 0 memory problem

### ISSUE THREAD

**Issue by soeaver** [hangzhaomit/semantic-segmentation-pytorch#13]
Hi, thanks for your repo.
I am using your code to train semantic segmentation task, but I find that the No. 0 GPU memory occupancy is much bigger than others, like this:
![image](https://user-images.githubusercontent.com/8629203/34072308-d320362c-e2bf-11e7-9359-2862b6ad506f.png)
This problem will not appear when training image classification, so I want to ask that do you have a method to solve this problem?
Thank you again.

**Comment by hangzhaomit** [comment]
This is because GPU0 is saving more intermediate variables, e.g. the output of encoder from all other gpus. One walk around is to put encoder and decoder into one module.
