### ISSUE TITLE
test.py not working properly

### ISSUE THREAD

**Issue by prashant0079** [hangzhaomit/semantic-segmentation-pytorch#16]
Can you tell what is the model id ? The models folder in your site is a bit confusing. Any help will be appreciated.

**Comment by gaceladri** [comment]
Hi guys,
Thank you very much for your work.

Same here. It's a little bit confusing how to use the code and how to segment new images outside the data.

Thanks a lot.

**Comment by hangzhaomit** [comment]
The download site is now cleaned.

**Comment by irwinherrmann** [comment]
I'm guessing the models are under pytorch and then the --arch_encoder and --arch_decoder are specified by the folder names. Even when I match everything, I still get errors.

python test.py --ckpt ckpt/ --id models/pytorch/baseline-resnet34_dilated8-c1bilinear --test_img demo/cars_1.JPG
Namespace(arch_decoder='c1_bilinear', arch_encoder='resnet34_dilated8', batch_size=1, ckpt='ckpt/', fc_dim=512, id='models/pytorch/baseline-resnet34_dilated8-c1bilinear', imgSize=384, num_class=150, num_val=-1, result='.', segSize=-1, suffix='_best.pth', test_img='demo/cars_1.JPG', visualize=0)
Loading weights for net_encoder
Traceback (most recent call last):
  File "test.py", line 162, in <module>
    main(args)
  File "test.py", line 96, in main
    weights=args.weights_encoder)
  File "/home/charles/Libraries/Segmentation/semantic-segmentation-pytorch/models.py", line 66, in build_encoder
    torch.load(weights, map_location=lambda storage, loc: storage))
  File "/home/charles/Libraries/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 355, in load_state_dict
    .format(name))
KeyError: 'unexpected key "features.0.weight" in state_dict'

I'm using Ubuntu 16.04, CUDA9, Python2.7, PyTorch 0.2.0_4

**Comment by fanyix** [comment]
I have successful experience only with the "resnet34_dilated8-psp_bilinear" model downloaded from [http://sceneparsing.csail.mit.edu/model/pytorch/baseline-resnet34_dilated8-psp_bilinear/](url).

Specifically, after you download the model from the above link (both the encoder and decoder network), create a directory, e.g. "checkpoints", under your project directory and then create a subdirectory "baseline-resnet34_dilated8-psp_bilinear" under "checkpoints", finally you put both "decoder_best.pth" and "encoder_best.pth" into this subdirectory. 

Then you can perform inference with `python test.py --ckpt ./checkpoints  --test_img ./scene.png --id baseline-resnet34_dilated8-psp_bilinear --arch_encoder resnet34_dilated8 --arch_decoder psp_bilinear` where "scene.png" should be replaced with the path of whatever images you'd like to test on. 

One small issue in the test.py is that the testing function would predicted starting from index 1 as shown in this line: [https://github.com/hangzhaomit/semantic-segmentation-pytorch/blob/4413e6ea4cf133a4aeb8b7be9cce43ff50215d4c/test.py#L57](url). However I guess you get more distinct colors for "semantically close" categories if you change this line to `pred_ = np.argmax(pred.numpy(), axis=0)`

**Comment by hangzhaomit** [comment]
Guys, thanks for raising this problem. And thanks @fanyix  for finding the +1 bug.
I modified the code a bit, and created a demo script demo_test.sh, to make life easier for everyone.
