### ISSUE TITLE
What is the speed of the prediction in test.py ?

### ISSUE THREAD

**Issue by rahulranjan07** [hangzhaomit/semantic-segmentation-pytorch#17]
I was wondering if anyone has tested the speed of the prediction in test.py. I tried it on a system with nvidia K80, cuda8.0 and it took around 2-3s for the prediction.

**Comment by hangzhaomit** [comment]
@rahulranjan07 
I have not tested thoroughly. According to my experience, most of time is spent on zoom() on CPU. And also, I am using 5 scales for testing, which is basically 5 times of a single pass.

**Comment by rahulranjan07** [comment]
Yes, I saw that. I would try to implement pytorch multiprocessing on these scales and check if it gives a better timing.
