### ISSUE TITLE
net.eval for dropout

### ISSUE THREAD

**Issue by iliadsouti** [hangzhaomit/semantic-segmentation-pytorch#18]
Using net.eval() for fixing the BN layer parameters make the dropout layer to act as in test time. Shouldn't only be used for BN layers only and not the whole network?

**Comment by hangzhaomit** [comment]
Our Resnet model does not have dropout, so it is fine here.

**Comment by iliadsouti** [comment]
Oh, my mistake I saw it in the code [code](https://github.com/hangzhaomit/semantic-segmentation-pytorch/blob/master/models.py#L231) and I thought it was used.
