### ISSUE TITLE
Class labels

### ISSUE THREAD

**Issue by DiegoOrtego** [hangzhaomit/semantic-segmentation-pytorch#7]
Hello! @hangzhaomit thanks for the ade20k pytorch code!

I wonder if you could provide me an idea of how I can map RGB colors from the *_seg.png annotations and the names of the 150 classes. I am planning to redefine the labels to train with different target classes and I am a little bit confused about this mapping.

Thanks in advance!

**Comment by hangzhaomit** [comment]
@DiegoOrtego  You can find the conversion code here :)
https://github.com/CSAILVision/sceneparsing/tree/master/convertFromADE

**Comment by DiegoOrtego** [comment]
Thanks! Great! So I get the labels with that conversion...but how can I know which class correspond each number or the original color,  i.e. is there any list with the 150 class labels sorted?

**Comment by hangzhaomit** [comment]
Is this what you want?
https://github.com/CSAILVision/sceneparsing/blob/master/objectInfo150.csv
https://github.com/CSAILVision/sceneparsing/tree/master/visualizationCode/color150

**Comment by DiegoOrtego** [comment]
Yes! defenitly the first file is what I need! Thanks @hangzhaomit !

**Comment by foobar8675** [comment]
Hi @hangzhaomit , first, thanks for putting all this together!

I was looking at the csv above, and grabbed one example for floor (and sky)

<img width="1070" alt="Screen Shot 2019-06-17 at 2 18 11 AM" src="https://user-images.githubusercontent.com/1685700/59585513-43ebab80-90a6-11e9-8bb1-faee2b92eec2.png">

and using that as a reference for one sample image `ADE_train_00000001.png` which in photoshop looks like the following when select the floor

<img width="804" alt="Screen Shot 2019-06-17 at 2 19 54 AM" src="https://user-images.githubusercontent.com/1685700/59585575-6d0c3c00-90a6-11e9-9b84-63f9df94fd9e.png">

in that screenshot, the floor has an rgb value of 3 for all channels, and assuming the index is used as the rgb value, shouldn't it be rgb(4,4,4) in photoshop?

I must be misunderstanding, can you help explain?

**Comment by MSiam** [comment]
In case someone is using the full dataset released for ADE20k, This would be the corresponding class_names:
[https://github.com/MSiam/AdaptiveMaskedProxies/blob/master/ade20k_classes.txt](url)
Since they had 3148 classes not just 150.
