### ISSUE TITLE
Pre-trained models in pytorch?

### ISSUE THREAD

**Issue by salemchen** [hangzhaomit/semantic-segmentation-pytorch#8]
Hi,
Are you going to release the pre-trained weights for one of the supported models in pytorch?

Thanks!

**Comment by hangzhaomit** [comment]
@salemchen Yes, I will release it in a couple of weeks. Keep an eye on it.

**Comment by fanser** [comment]
Hi,
Where can I download your pre-trained model?

Thanks!
